export const ADD_PRODUCT_BASKET = 'ADD_PRODUCT_BASKET'

export const GET_NUMBERS_IN_BASKET = 'GET_NUMBERS_IN_BASKET'

export const INCREASE_QUANTITY = 'INCREASE_QUANTITY'

export const DECREASE_QUANTITY = 'DECREASE_QUANTITY'

export const REMOVE_PRODUCT = 'REMOVE_PRODUCT'
